[aws]
disabled = true

[cmd_duration]
min_time = 5_000

[conda]
disabled = true

[crystal]
disabled = true

[directory]
style = "bold green"

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_commit]
disabled = true

[git_status]
conflicted = "=${count}"
deleted = "✘${count}"
modified = "!${count}"
renamed = "»${count}"
staged = "+${count}"
stashed = '\$${count}'
untracked = "?${count}"

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = false
symbol = '⎈ '
style = 'cyan'

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true

[time]
disabled = false
format = "[$time]($style) "

[zig]
disabled = true


